### ISSUE TITLE
Avast Anti Virus still does not allow Windows program download.

### ISSUE THREAD

**Issue by darwinpetersen** [oxen-io/oxen-electron-gui-wallet#237]

**Comment by kylezs** [comment]
Closing this issue as it's old, raise another or reach out on the Community Telegram if you need help. There's also this guide: https://docs.oxen.io/using-the-oxen-blockchain/oxen-wallet-guides/preparing-for-gui-wallet-setup-windows for getting around Bitdefender, a similar process can likely be used for Avast. If you download from the correct location, it should be safe to ignore the warnings thrown by the AV.
